### ISSUE TITLE
Question: How do you setup the web project without the classic Initialize Firebase script

### ISSUE THREAD

**Issue by Rovel** [firebase/friendlypix-web#15]
Hey @nicolasgarnier,

How do you guys make the firebase init vars configurable only by using firebase use add --
and not hard coding the vars as the classic docs say as below:

```
<script src="https://www.gstatic.com/firebasejs/4.6.2/firebase.js"></script>
<script>
  // Initialize Firebase
  var config = {
    apiKey: "<cdscdscd>",
    authDomain: "<cdscdscd>",
    databaseURL: "<cdscdscd>",
    projectId: "<cdscdscd>",
    storageBucket: "<cdscdscd>",
    messagingSenderId: "<cdscdscd>"
  };
  firebase.initializeApp(config);
</script>
```

I analysed this repo code but I wanted a clearer info around this, since is a nice setup for a multi env project that needs different db, storage and others.

Can I query the firebase project to change some logo image too, ex: if is a dev env show my dev logo at home screen.

Thanks.

**Comment by nicolasgarnier** [comment]
Instead of the "static" / inline firebase init you can use the init script:
```html
<script src="/__/firebase/init.js"></script>
```

The init.js script is only available in a Firebase Hosting environment though so you have to test locally using `firebase serve` and deploy using `firebase deploy` and use Firebase Hosting as your hosting provider.

If you plan on using your own hosting servers you can generate a JSON file containing the Firebase config using ` firebase setup:web --json > ./frontend/firebase-config.json`
