### ISSUE TITLE
Upload Videos

### ISSUE THREAD

**Issue by rohanath** [firebase/friendlypix-web#37]
I am looking to upload videos through this application. I can see that the storage.rules file has a rule that prevents that from happening. My question is where else do I need to make changes to be able to upload videos because right now, it does not even allow me to select them.

**Comment by nicolasgarnier** [comment]
There are 3 things to change:
 - The security rules will need to be changed. Right now they only allow images MIME types `request.resource.contentType.matches('image/.*')` and files of maximum 5MB `request.resource.size < maxSizeMB * 1024 * 1024`
 - In [Uploader.js](https://github.com/firebase/friendlypix-web/blob/master/src/Uploader.js#L141) there are multiple places where we rely on the file to be an image: The image is displayed in the UI before being uploaded and we're generating the thumbnail and converting the image to JPEG on the client, in that file.
 - in the [HTML file‘(https://github.com/firebase/friendlypix-web/blob/master/src/index.html#L137) the file picker only allows images to be selected. You just need to change the MIME type there.

**Comment by rohanath** [comment]
Thank you for your reply

**Comment by amit8121** [comment]
@rohanath I'm also looking to do the same, since quite a few days but without much success... Do you mind sharing how to achieve this...

**Comment by rohanath** [comment]
Hey Amit,

I changed the MIME types which allows me to select videos from the file
picker. I believe there are a lot more changes to be made in uploader.js to
make this work. I have not been able to achieve that yet but you can try
the three suggestions specifies by Nicolas.

Thanks,
Rohan

**Comment by sonu96** [comment]
Hey @nicolasgarnier ,
Can you please tell me in depth on how to make this app to app to allow video uploading. I have  changed the html file and security rules of firebase. I have also tried to change MIME types in Uploader.js in multiple places to allow video

**Comment by nicolasgarnier** [comment]
@sonu96 Are you seeing any errors, facing any specific problems?
I also mentioned re-working the upload mechanism (in Uploader.js) would be quite some work
because right now we're generating a thumbnail and image on the client and
this all needs to be changed for videos, have you also done that?

You'll also need to display the videos rather than the images in the feeds,
check out the video HTML tag (although that will only work on modern
browsers and if you want to support me you need to fallback to using some
kind of flash reader). In the app this is where we display a post: https://github.com/firebase/friendlypix-web/blob/master/src/Post.js and this is where we display the thumbnail of the image specifically: https://github.com/firebase/friendlypix-web/blob/master/src/Post.js#L228-L234 and this is where the HTML template gets generated: https://github.com/firebase/friendlypix-web/blob/master/src/Post.js#L481

I won't be able to provide code for this whole solution as it's too much work that's unrelated to Firebase but I'm happy to give some pointers when it relates to the app.
