### ISSUE TITLE
How to add video upload functionality

### ISSUE THREAD

**Issue by sonu96** [firebase/friendlypix-web#44]
Hey @nicolasgarnier ,
Can you please tell me in depth on how to make this app to allow video uploading. I have changed the html file and security rules of firebase. I have also tried to change MIME types in Uploader.js in multiple places to allow video.
I followed all the 3 things to change which you mentioned before but couldn't find a solution

**Comment by nicolasgarnier** [comment]
Are you seeing any errors, facing any specific problems?
I also mentionned re-working the upload mechanism would be quite some work
because right now we're generating a thumbnail and image on the client and
this all needs to be changed, have you also done that?

You'll also need to display the videos rather than the images in the feeds,
check out the video HTML tag (although that will only work on modern
browsers and if you want to support me you need to fallback to using some
kind of flash reader)

**Comment by nicolasgarnier** [comment]
Let's close and use https://github.com/firebase/friendlypix-web/issues/37 instead
